version: '2.3'
services:
  registry:
    build: .
    volumes:
      - .:/app
    # environment:
    #   LOG_LEVEL: 'debug'
    command: "ruby ./registry.rb"

  node:
    build: .
    volumes:
      - .:/app
    environment:
      PORT: 3000
      LOSS_RATE: 0.3
      AVERAGE_DELAY: 3
      TIMEOUT: 3
      # LOG_LEVEL: 'debug'
    scale: 2
